services:
  token-db:
    image: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U nexa -d nexa-token" ]
      interval: 10s
      retries: 5
      timeout: 30s
    environment:
      - POSTGRES_DB=nexa-token
      - POSTGRES_USER=nexa
      - POSTGRES_PASSWORD=nexa
    networks:
      - nt_network
  nexa-token-migrate:
    build:
      dockerfile: ./docker/migrate.Dockerfile
    restart: on-failure
    depends_on:
      token-db:
        condition: service_healthy
    environment:
      - PG_ADDRESS=token-db
      - PG_USERNAME=nexa
      - PG_PASSWORD=nexa
      - PG_DB_NAME=nexa-token
      - PG_IS_SECURE=false
    networks:
      - nt_network
  nexa-token:
    build:
      dockerfile: ./docker/app.Dockerfile
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "grpc_health_probe", "-addr=localhost:8080"]
      retries: 3
      interval: 60s
      start_period: 5s
      timeout: 30s
    depends_on:
      nexa-token-migrate:
        condition: service_completed_successfully
        restart: false
    environment:
      - PG_ADDRESS=token-db
      - PG_USERNAME=nexa
      - PG_PASSWORD=nexa
      - PG_DB_NAME=nexa-token
      - PG_PARAMETER=application_name=nexa-token
      - PG_IS_SECURE=false
#      - OTLP_GRPC_COLLECTOR_ADDRESS=jaeger:4317
#      - GENERAL_TOKEN_EXPIRATION=24h
#    ports:
#      - "8080:8080"
#      - "8081"
    networks:
      - nt_network
networks:
  nt_network:
    driver: bridge
