include:
  - ../authorization/docker-compose.yml
  - ../authentication/docker-compose.yml
  - ../token/docker-compose.yml
  - ../mailer/docker-compose.yml

services:
  file-db:
    image: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U nexa -d nexa-file" ]
      interval: 5s
      retries: 10
    environment:
      - POSTGRES_DB=nexa-file
      - POSTGRES_USER=nexa
      - POSTGRES_PASSWORD=nexa
    ports:
      - "5432:5432"
    networks:
      - nf_network
  minio:
    image: quay.io/minio/minio
    healthcheck:
      test: ["CMD-SHELL", "mc ready local"]
      retries: 10
      interval: 5s
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=rootroot123
    ports:
      - "9000:9000"
      - "9001:9001"
    command: 'server /data --console-address ":9001"'
    networks:
      - nf_network
  jaeger:
    image: jaegertracing/all-in-one:1.58
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    networks:
      - nf_network
  nexa-storage-migrate:
    build:
      dockerfile: ./docker/migrate.Dockerfile
    restart: on-failure
    depends_on:
      file-db:
        condition: service_healthy
    environment:
      - PG_ADDRESS=file-db
      - PG_USERNAME=nexa
      - PG_PASSWORD=nexa
      - PG_DB_NAME=nexa-file
      - PG_IS_SECURE=false
    networks:
      - nf_network
  storage-token_generator:
    build:
      context: ../../token_generator/
      dockerfile: Dockerfile
    entrypoint: /bin/sh -c "./main > /output/token.txt"
    volumes:
      - storage-token_output:/output
  nexa-storage-seed:
    build:
      dockerfile: ./docker/seed.Dockerfile
    restart: on-failure
    depends_on:
      nexa-storage-migrate:
        condition: service_completed_successfully
      storage-token_generator:
        condition: service_completed_successfully
      nexa-authz:
        condition: service_healthy
    environment:
      - PG_ADDRESS=file-db
      - PG_USERNAME=nexa
      - PG_PASSWORD=nexa
      - PG_DB_NAME=nexa-file
      - PG_IS_SECURE=false
      - AUTHZ_SERVICE_ADDR=nexa-authz:8080
    networks:
      - nf_network
    volumes:
      - storage-token_output:/output
networks:
  nf_network:
    driver: bridge

volumes:
  storage-token_output: