// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UOWBlockMock is an autogenerated mock type for the UOWBlock type
type UOWBlockMock[T interface{}] struct {
	mock.Mock
}

type UOWBlockMock_Expecter[T interface{}] struct {
	mock *mock.Mock
}

func (_m *UOWBlockMock[T]) EXPECT() *UOWBlockMock_Expecter[T] {
	return &UOWBlockMock_Expecter[T]{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *UOWBlockMock[T]) Execute(_a0 context.Context, _a1 T) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, T) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UOWBlockMock_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type UOWBlockMock_Execute_Call[T interface{}] struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 T
func (_e *UOWBlockMock_Expecter[T]) Execute(_a0 interface{}, _a1 interface{}) *UOWBlockMock_Execute_Call[T] {
	return &UOWBlockMock_Execute_Call[T]{Call: _e.mock.On("Execute", _a0, _a1)}
}

func (_c *UOWBlockMock_Execute_Call[T]) Run(run func(_a0 context.Context, _a1 T)) *UOWBlockMock_Execute_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(T))
	})
	return _c
}

func (_c *UOWBlockMock_Execute_Call[T]) Return(_a0 error) *UOWBlockMock_Execute_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UOWBlockMock_Execute_Call[T]) RunAndReturn(run func(context.Context, T) error) *UOWBlockMock_Execute_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewUOWBlockMock creates a new instance of UOWBlockMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUOWBlockMock[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *UOWBlockMock[T] {
	mock := &UOWBlockMock[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
