// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "nexa/services/mailer/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	repo "nexa/shared/util/repo"

	types "nexa/shared/types"
)

// TagMock is an autogenerated mock type for the ITag type
type TagMock struct {
	mock.Mock
}

type TagMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TagMock) EXPECT() *TagMock_Expecter {
	return &TagMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, tag
func (_m *TagMock) Create(ctx context.Context, tag *entity.Tag) error {
	ret := _m.Called(ctx, tag)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Tag) error); ok {
		r0 = rf(ctx, tag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TagMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TagMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tag *entity.Tag
func (_e *TagMock_Expecter) Create(ctx interface{}, tag interface{}) *TagMock_Create_Call {
	return &TagMock_Create_Call{Call: _e.mock.On("Create", ctx, tag)}
}

func (_c *TagMock_Create_Call) Run(run func(ctx context.Context, tag *entity.Tag)) *TagMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Tag))
	})
	return _c
}

func (_c *TagMock_Create_Call) Return(_a0 error) *TagMock_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TagMock_Create_Call) RunAndReturn(run func(context.Context, *entity.Tag) error) *TagMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIds provides a mock function with given fields: ctx, ids
func (_m *TagMock) FindByIds(ctx context.Context, ids ...types.Id) ([]entity.Tag, error) {
	_va := make([]interface{}, len(ids))
	for _i := range ids {
		_va[_i] = ids[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FindByIds")
	}

	var r0 []entity.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...types.Id) ([]entity.Tag, error)); ok {
		return rf(ctx, ids...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...types.Id) []entity.Tag); ok {
		r0 = rf(ctx, ids...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...types.Id) error); ok {
		r1 = rf(ctx, ids...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TagMock_FindByIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIds'
type TagMock_FindByIds_Call struct {
	*mock.Call
}

// FindByIds is a helper method to define mock.On call
//   - ctx context.Context
//   - ids ...types.Id
func (_e *TagMock_Expecter) FindByIds(ctx interface{}, ids ...interface{}) *TagMock_FindByIds_Call {
	return &TagMock_FindByIds_Call{Call: _e.mock.On("FindByIds",
		append([]interface{}{ctx}, ids...)...)}
}

func (_c *TagMock_FindByIds_Call) Run(run func(ctx context.Context, ids ...types.Id)) *TagMock_FindByIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]types.Id, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(types.Id)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *TagMock_FindByIds_Call) Return(_a0 []entity.Tag, _a1 error) *TagMock_FindByIds_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TagMock_FindByIds_Call) RunAndReturn(run func(context.Context, ...types.Id) ([]entity.Tag, error)) *TagMock_FindByIds_Call {
	_c.Call.Return(run)
	return _c
}

// FindByName provides a mock function with given fields: ctx, name
func (_m *TagMock) FindByName(ctx context.Context, name string) (*entity.Tag, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *entity.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Tag, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Tag); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TagMock_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type TagMock_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *TagMock_Expecter) FindByName(ctx interface{}, name interface{}) *TagMock_FindByName_Call {
	return &TagMock_FindByName_Call{Call: _e.mock.On("FindByName", ctx, name)}
}

func (_c *TagMock_FindByName_Call) Run(run func(ctx context.Context, name string)) *TagMock_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TagMock_FindByName_Call) Return(_a0 *entity.Tag, _a1 error) *TagMock_FindByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TagMock_FindByName_Call) RunAndReturn(run func(context.Context, string) (*entity.Tag, error)) *TagMock_FindByName_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, query
func (_m *TagMock) Get(ctx context.Context, query repo.QueryParameter) (repo.PaginatedResult[entity.Tag], error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 repo.PaginatedResult[entity.Tag]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repo.QueryParameter) (repo.PaginatedResult[entity.Tag], error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repo.QueryParameter) repo.PaginatedResult[entity.Tag]); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(repo.PaginatedResult[entity.Tag])
	}

	if rf, ok := ret.Get(1).(func(context.Context, repo.QueryParameter) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TagMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type TagMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - query repo.QueryParameter
func (_e *TagMock_Expecter) Get(ctx interface{}, query interface{}) *TagMock_Get_Call {
	return &TagMock_Get_Call{Call: _e.mock.On("Get", ctx, query)}
}

func (_c *TagMock_Get_Call) Run(run func(ctx context.Context, query repo.QueryParameter)) *TagMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repo.QueryParameter))
	})
	return _c
}

func (_c *TagMock_Get_Call) Return(_a0 repo.PaginatedResult[entity.Tag], _a1 error) *TagMock_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TagMock_Get_Call) RunAndReturn(run func(context.Context, repo.QueryParameter) (repo.PaginatedResult[entity.Tag], error)) *TagMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function with given fields: ctx, tag
func (_m *TagMock) Patch(ctx context.Context, tag *entity.PatchedTag) error {
	ret := _m.Called(ctx, tag)

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.PatchedTag) error); ok {
		r0 = rf(ctx, tag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TagMock_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type TagMock_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - ctx context.Context
//   - tag *entity.PatchedTag
func (_e *TagMock_Expecter) Patch(ctx interface{}, tag interface{}) *TagMock_Patch_Call {
	return &TagMock_Patch_Call{Call: _e.mock.On("Patch", ctx, tag)}
}

func (_c *TagMock_Patch_Call) Run(run func(ctx context.Context, tag *entity.PatchedTag)) *TagMock_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.PatchedTag))
	})
	return _c
}

func (_c *TagMock_Patch_Call) Return(_a0 error) *TagMock_Patch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TagMock_Patch_Call) RunAndReturn(run func(context.Context, *entity.PatchedTag) error) *TagMock_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: ctx, id
func (_m *TagMock) Remove(ctx context.Context, id types.Id) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.Id) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TagMock_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type TagMock_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - id types.Id
func (_e *TagMock_Expecter) Remove(ctx interface{}, id interface{}) *TagMock_Remove_Call {
	return &TagMock_Remove_Call{Call: _e.mock.On("Remove", ctx, id)}
}

func (_c *TagMock_Remove_Call) Run(run func(ctx context.Context, id types.Id)) *TagMock_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.Id))
	})
	return _c
}

func (_c *TagMock_Remove_Call) Return(_a0 error) *TagMock_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TagMock_Remove_Call) RunAndReturn(run func(context.Context, types.Id) error) *TagMock_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// NewTagMock creates a new instance of TagMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTagMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TagMock {
	mock := &TagMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
