// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: token.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	proto "nexa/shared/proto"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Token_Request_FullMethodName       = "/services.authentication.schema.proto.v1.Token/Request"
	Token_Verify_FullMethodName        = "/services.authentication.schema.proto.v1.Token/Verify"
	Token_AddUsage_FullMethodName      = "/services.authentication.schema.proto.v1.Token/AddUsage"
	Token_RemoveUsage_FullMethodName   = "/services.authentication.schema.proto.v1.Token/RemoveUsage"
	Token_UpdateUsage_FullMethodName   = "/services.authentication.schema.proto.v1.Token/UpdateUsage"
	Token_FindUsage_FullMethodName     = "/services.authentication.schema.proto.v1.Token/FindUsage"
	Token_FindAllUsages_FullMethodName = "/services.authentication.schema.proto.v1.Token/FindAllUsages"
)

// TokenClient is the client API for Token service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokenClient interface {
	Request(ctx context.Context, in *RequestInput, opts ...grpc.CallOption) (*RequestOutput, error)
	Verify(ctx context.Context, in *VerifyInput, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AddUsage(ctx context.Context, in *AddUsageInput, opts ...grpc.CallOption) (*AddUsageOutput, error)
	RemoveUsage(ctx context.Context, in *RemoveUsageInput, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateUsage(ctx context.Context, in *UpdateUsageInput, opts ...grpc.CallOption) (*emptypb.Empty, error)
	FindUsage(ctx context.Context, in *FindUsageInput, opts ...grpc.CallOption) (*TokenUsageResponse, error)
	FindAllUsages(ctx context.Context, in *proto.PagedElementInput, opts ...grpc.CallOption) (*FindAllUsagesOutput, error)
}

type tokenClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenClient(cc grpc.ClientConnInterface) TokenClient {
	return &tokenClient{cc}
}

func (c *tokenClient) Request(ctx context.Context, in *RequestInput, opts ...grpc.CallOption) (*RequestOutput, error) {
	out := new(RequestOutput)
	err := c.cc.Invoke(ctx, Token_Request_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenClient) Verify(ctx context.Context, in *VerifyInput, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Token_Verify_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenClient) AddUsage(ctx context.Context, in *AddUsageInput, opts ...grpc.CallOption) (*AddUsageOutput, error) {
	out := new(AddUsageOutput)
	err := c.cc.Invoke(ctx, Token_AddUsage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenClient) RemoveUsage(ctx context.Context, in *RemoveUsageInput, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Token_RemoveUsage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenClient) UpdateUsage(ctx context.Context, in *UpdateUsageInput, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Token_UpdateUsage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenClient) FindUsage(ctx context.Context, in *FindUsageInput, opts ...grpc.CallOption) (*TokenUsageResponse, error) {
	out := new(TokenUsageResponse)
	err := c.cc.Invoke(ctx, Token_FindUsage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenClient) FindAllUsages(ctx context.Context, in *proto.PagedElementInput, opts ...grpc.CallOption) (*FindAllUsagesOutput, error) {
	out := new(FindAllUsagesOutput)
	err := c.cc.Invoke(ctx, Token_FindAllUsages_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenServer is the server API for Token service.
// All implementations must embed UnimplementedTokenServer
// for forward compatibility
type TokenServer interface {
	Request(context.Context, *RequestInput) (*RequestOutput, error)
	Verify(context.Context, *VerifyInput) (*emptypb.Empty, error)
	AddUsage(context.Context, *AddUsageInput) (*AddUsageOutput, error)
	RemoveUsage(context.Context, *RemoveUsageInput) (*emptypb.Empty, error)
	UpdateUsage(context.Context, *UpdateUsageInput) (*emptypb.Empty, error)
	FindUsage(context.Context, *FindUsageInput) (*TokenUsageResponse, error)
	FindAllUsages(context.Context, *proto.PagedElementInput) (*FindAllUsagesOutput, error)
	mustEmbedUnimplementedTokenServer()
}

// UnimplementedTokenServer must be embedded to have forward compatible implementations.
type UnimplementedTokenServer struct {
}

func (UnimplementedTokenServer) Request(context.Context, *RequestInput) (*RequestOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedTokenServer) Verify(context.Context, *VerifyInput) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedTokenServer) AddUsage(context.Context, *AddUsageInput) (*AddUsageOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUsage not implemented")
}
func (UnimplementedTokenServer) RemoveUsage(context.Context, *RemoveUsageInput) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveUsage not implemented")
}
func (UnimplementedTokenServer) UpdateUsage(context.Context, *UpdateUsageInput) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUsage not implemented")
}
func (UnimplementedTokenServer) FindUsage(context.Context, *FindUsageInput) (*TokenUsageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindUsage not implemented")
}
func (UnimplementedTokenServer) FindAllUsages(context.Context, *proto.PagedElementInput) (*FindAllUsagesOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAllUsages not implemented")
}
func (UnimplementedTokenServer) mustEmbedUnimplementedTokenServer() {}

// UnsafeTokenServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenServer will
// result in compilation errors.
type UnsafeTokenServer interface {
	mustEmbedUnimplementedTokenServer()
}

func RegisterTokenServer(s grpc.ServiceRegistrar, srv TokenServer) {
	s.RegisterService(&Token_ServiceDesc, srv)
}

func _Token_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Token_Request_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServer).Request(ctx, req.(*RequestInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Token_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Token_Verify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServer).Verify(ctx, req.(*VerifyInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Token_AddUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUsageInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServer).AddUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Token_AddUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServer).AddUsage(ctx, req.(*AddUsageInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Token_RemoveUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveUsageInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServer).RemoveUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Token_RemoveUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServer).RemoveUsage(ctx, req.(*RemoveUsageInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Token_UpdateUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUsageInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServer).UpdateUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Token_UpdateUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServer).UpdateUsage(ctx, req.(*UpdateUsageInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Token_FindUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindUsageInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServer).FindUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Token_FindUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServer).FindUsage(ctx, req.(*FindUsageInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Token_FindAllUsages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto.PagedElementInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServer).FindAllUsages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Token_FindAllUsages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServer).FindAllUsages(ctx, req.(*proto.PagedElementInput))
	}
	return interceptor(ctx, in, info, handler)
}

// Token_ServiceDesc is the grpc.ServiceDesc for Token service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Token_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.authentication.schema.proto.v1.Token",
	HandlerType: (*TokenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Request",
			Handler:    _Token_Request_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _Token_Verify_Handler,
		},
		{
			MethodName: "AddUsage",
			Handler:    _Token_AddUsage_Handler,
		},
		{
			MethodName: "RemoveUsage",
			Handler:    _Token_RemoveUsage_Handler,
		},
		{
			MethodName: "UpdateUsage",
			Handler:    _Token_UpdateUsage_Handler,
		},
		{
			MethodName: "FindUsage",
			Handler:    _Token_FindUsage_Handler,
		},
		{
			MethodName: "FindAllUsages",
			Handler:    _Token_FindAllUsages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "token.proto",
}
