with-expecter: true
#inpackage: true
dir: "{{.InterfaceDir}}/mocks"
mockname: '{{trimPrefix .InterfaceName "I"}}Mock'
outpkg: 'mocks'
packages:
  nexa/services/mailer/internal/domain/repository:
    config:
      recursive: true
      all: true
  nexa/services/mailer/internal/domain/external:
    config:
      recursive: true
      all: true
  nexa/services/mailer/internal/domain/service:
    config:
      recursive: true
      all: true