with-expecter: true
inpackage: true
dir: "{{.InterfaceDir}}/mocks"
mockname: '{{trimPrefix .InterfaceName "I"}}Mock'
packages:
  nexa/services/mailer/internal/domain/repository:
    config:
      recursive: true
      all: true